// Code generated by entc, DO NOT EDIT.

package mdrekvizit

import (
	"fynegui/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Namerus applies equality check predicate on the "namerus" field. It's identical to NamerusEQ.
func Namerus(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNamerus), v))
	})
}

// Nameeng applies equality check predicate on the "nameeng" field. It's identical to NameengEQ.
func Nameeng(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNameeng), v))
	})
}

// Synonym applies equality check predicate on the "synonym" field. It's identical to SynonymEQ.
func Synonym(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSynonym), v))
	})
}

// Por applies equality check predicate on the "por" field. It's identical to PorEQ.
func Por(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPor), v))
	})
}

// WidthElem applies equality check predicate on the "widthElem" field. It's identical to WidthElemEQ.
func WidthElem(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWidthElem), v))
	})
}

// WidthSpisok applies equality check predicate on the "widthSpisok" field. It's identical to WidthSpisokEQ.
func WidthSpisok(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWidthSpisok), v))
	})
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldType), v))
	})
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOwnerID), v))
	})
}

// NamerusEQ applies the EQ predicate on the "namerus" field.
func NamerusEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNamerus), v))
	})
}

// NamerusNEQ applies the NEQ predicate on the "namerus" field.
func NamerusNEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNamerus), v))
	})
}

// NamerusIn applies the In predicate on the "namerus" field.
func NamerusIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNamerus), v...))
	})
}

// NamerusNotIn applies the NotIn predicate on the "namerus" field.
func NamerusNotIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNamerus), v...))
	})
}

// NamerusGT applies the GT predicate on the "namerus" field.
func NamerusGT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNamerus), v))
	})
}

// NamerusGTE applies the GTE predicate on the "namerus" field.
func NamerusGTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNamerus), v))
	})
}

// NamerusLT applies the LT predicate on the "namerus" field.
func NamerusLT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNamerus), v))
	})
}

// NamerusLTE applies the LTE predicate on the "namerus" field.
func NamerusLTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNamerus), v))
	})
}

// NamerusContains applies the Contains predicate on the "namerus" field.
func NamerusContains(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNamerus), v))
	})
}

// NamerusHasPrefix applies the HasPrefix predicate on the "namerus" field.
func NamerusHasPrefix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNamerus), v))
	})
}

// NamerusHasSuffix applies the HasSuffix predicate on the "namerus" field.
func NamerusHasSuffix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNamerus), v))
	})
}

// NamerusEqualFold applies the EqualFold predicate on the "namerus" field.
func NamerusEqualFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNamerus), v))
	})
}

// NamerusContainsFold applies the ContainsFold predicate on the "namerus" field.
func NamerusContainsFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNamerus), v))
	})
}

// NameengEQ applies the EQ predicate on the "nameeng" field.
func NameengEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNameeng), v))
	})
}

// NameengNEQ applies the NEQ predicate on the "nameeng" field.
func NameengNEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNameeng), v))
	})
}

// NameengIn applies the In predicate on the "nameeng" field.
func NameengIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNameeng), v...))
	})
}

// NameengNotIn applies the NotIn predicate on the "nameeng" field.
func NameengNotIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNameeng), v...))
	})
}

// NameengGT applies the GT predicate on the "nameeng" field.
func NameengGT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNameeng), v))
	})
}

// NameengGTE applies the GTE predicate on the "nameeng" field.
func NameengGTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNameeng), v))
	})
}

// NameengLT applies the LT predicate on the "nameeng" field.
func NameengLT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNameeng), v))
	})
}

// NameengLTE applies the LTE predicate on the "nameeng" field.
func NameengLTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNameeng), v))
	})
}

// NameengContains applies the Contains predicate on the "nameeng" field.
func NameengContains(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNameeng), v))
	})
}

// NameengHasPrefix applies the HasPrefix predicate on the "nameeng" field.
func NameengHasPrefix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNameeng), v))
	})
}

// NameengHasSuffix applies the HasSuffix predicate on the "nameeng" field.
func NameengHasSuffix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNameeng), v))
	})
}

// NameengEqualFold applies the EqualFold predicate on the "nameeng" field.
func NameengEqualFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNameeng), v))
	})
}

// NameengContainsFold applies the ContainsFold predicate on the "nameeng" field.
func NameengContainsFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNameeng), v))
	})
}

// SynonymEQ applies the EQ predicate on the "synonym" field.
func SynonymEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSynonym), v))
	})
}

// SynonymNEQ applies the NEQ predicate on the "synonym" field.
func SynonymNEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSynonym), v))
	})
}

// SynonymIn applies the In predicate on the "synonym" field.
func SynonymIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSynonym), v...))
	})
}

// SynonymNotIn applies the NotIn predicate on the "synonym" field.
func SynonymNotIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSynonym), v...))
	})
}

// SynonymGT applies the GT predicate on the "synonym" field.
func SynonymGT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSynonym), v))
	})
}

// SynonymGTE applies the GTE predicate on the "synonym" field.
func SynonymGTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSynonym), v))
	})
}

// SynonymLT applies the LT predicate on the "synonym" field.
func SynonymLT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSynonym), v))
	})
}

// SynonymLTE applies the LTE predicate on the "synonym" field.
func SynonymLTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSynonym), v))
	})
}

// SynonymContains applies the Contains predicate on the "synonym" field.
func SynonymContains(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSynonym), v))
	})
}

// SynonymHasPrefix applies the HasPrefix predicate on the "synonym" field.
func SynonymHasPrefix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSynonym), v))
	})
}

// SynonymHasSuffix applies the HasSuffix predicate on the "synonym" field.
func SynonymHasSuffix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSynonym), v))
	})
}

// SynonymEqualFold applies the EqualFold predicate on the "synonym" field.
func SynonymEqualFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSynonym), v))
	})
}

// SynonymContainsFold applies the ContainsFold predicate on the "synonym" field.
func SynonymContainsFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSynonym), v))
	})
}

// PorEQ applies the EQ predicate on the "por" field.
func PorEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPor), v))
	})
}

// PorNEQ applies the NEQ predicate on the "por" field.
func PorNEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPor), v))
	})
}

// PorIn applies the In predicate on the "por" field.
func PorIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPor), v...))
	})
}

// PorNotIn applies the NotIn predicate on the "por" field.
func PorNotIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPor), v...))
	})
}

// PorGT applies the GT predicate on the "por" field.
func PorGT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPor), v))
	})
}

// PorGTE applies the GTE predicate on the "por" field.
func PorGTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPor), v))
	})
}

// PorLT applies the LT predicate on the "por" field.
func PorLT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPor), v))
	})
}

// PorLTE applies the LTE predicate on the "por" field.
func PorLTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPor), v))
	})
}

// PorContains applies the Contains predicate on the "por" field.
func PorContains(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPor), v))
	})
}

// PorHasPrefix applies the HasPrefix predicate on the "por" field.
func PorHasPrefix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPor), v))
	})
}

// PorHasSuffix applies the HasSuffix predicate on the "por" field.
func PorHasSuffix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPor), v))
	})
}

// PorEqualFold applies the EqualFold predicate on the "por" field.
func PorEqualFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPor), v))
	})
}

// PorContainsFold applies the ContainsFold predicate on the "por" field.
func PorContainsFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPor), v))
	})
}

// WidthElemEQ applies the EQ predicate on the "widthElem" field.
func WidthElemEQ(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWidthElem), v))
	})
}

// WidthElemNEQ applies the NEQ predicate on the "widthElem" field.
func WidthElemNEQ(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldWidthElem), v))
	})
}

// WidthElemIn applies the In predicate on the "widthElem" field.
func WidthElemIn(vs ...float64) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldWidthElem), v...))
	})
}

// WidthElemNotIn applies the NotIn predicate on the "widthElem" field.
func WidthElemNotIn(vs ...float64) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldWidthElem), v...))
	})
}

// WidthElemGT applies the GT predicate on the "widthElem" field.
func WidthElemGT(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldWidthElem), v))
	})
}

// WidthElemGTE applies the GTE predicate on the "widthElem" field.
func WidthElemGTE(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldWidthElem), v))
	})
}

// WidthElemLT applies the LT predicate on the "widthElem" field.
func WidthElemLT(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldWidthElem), v))
	})
}

// WidthElemLTE applies the LTE predicate on the "widthElem" field.
func WidthElemLTE(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldWidthElem), v))
	})
}

// WidthSpisokEQ applies the EQ predicate on the "widthSpisok" field.
func WidthSpisokEQ(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWidthSpisok), v))
	})
}

// WidthSpisokNEQ applies the NEQ predicate on the "widthSpisok" field.
func WidthSpisokNEQ(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldWidthSpisok), v))
	})
}

// WidthSpisokIn applies the In predicate on the "widthSpisok" field.
func WidthSpisokIn(vs ...float64) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldWidthSpisok), v...))
	})
}

// WidthSpisokNotIn applies the NotIn predicate on the "widthSpisok" field.
func WidthSpisokNotIn(vs ...float64) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldWidthSpisok), v...))
	})
}

// WidthSpisokGT applies the GT predicate on the "widthSpisok" field.
func WidthSpisokGT(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldWidthSpisok), v))
	})
}

// WidthSpisokGTE applies the GTE predicate on the "widthSpisok" field.
func WidthSpisokGTE(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldWidthSpisok), v))
	})
}

// WidthSpisokLT applies the LT predicate on the "widthSpisok" field.
func WidthSpisokLT(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldWidthSpisok), v))
	})
}

// WidthSpisokLTE applies the LTE predicate on the "widthSpisok" field.
func WidthSpisokLTE(v float64) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldWidthSpisok), v))
	})
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldType), v))
	})
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldType), v))
	})
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldType), v...))
	})
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldType), v...))
	})
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldType), v))
	})
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldType), v))
	})
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldType), v))
	})
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldType), v))
	})
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldType), v))
	})
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldType), v))
	})
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldType), v))
	})
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldType), v))
	})
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldType), v))
	})
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOwnerID), v))
	})
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOwnerID), v))
	})
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldOwnerID), v...))
	})
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...string) predicate.MDRekvizit {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDRekvizit(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldOwnerID), v...))
	})
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldOwnerID), v))
	})
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldOwnerID), v))
	})
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldOwnerID), v))
	})
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldOwnerID), v))
	})
}

// OwnerIDContains applies the Contains predicate on the "owner_id" field.
func OwnerIDContains(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldOwnerID), v))
	})
}

// OwnerIDHasPrefix applies the HasPrefix predicate on the "owner_id" field.
func OwnerIDHasPrefix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldOwnerID), v))
	})
}

// OwnerIDHasSuffix applies the HasSuffix predicate on the "owner_id" field.
func OwnerIDHasSuffix(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldOwnerID), v))
	})
}

// OwnerIDIsNil applies the IsNil predicate on the "owner_id" field.
func OwnerIDIsNil() predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldOwnerID)))
	})
}

// OwnerIDNotNil applies the NotNil predicate on the "owner_id" field.
func OwnerIDNotNil() predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldOwnerID)))
	})
}

// OwnerIDEqualFold applies the EqualFold predicate on the "owner_id" field.
func OwnerIDEqualFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldOwnerID), v))
	})
}

// OwnerIDContainsFold applies the ContainsFold predicate on the "owner_id" field.
func OwnerIDContainsFold(v string) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldOwnerID), v))
	})
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.MDTabel) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MDRekvizit) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MDRekvizit) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MDRekvizit) predicate.MDRekvizit {
	return predicate.MDRekvizit(func(s *sql.Selector) {
		p(s.Not())
	})
}
