// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MdRekvizitsColumns holds the columns for the "md_rekvizits" table.
	MdRekvizitsColumns = []*schema.Column{
		{Name: "ID", Type: field.TypeString, Unique: true, Size: 36},
		{Name: "Nameeng", Type: field.TypeString, Size: 300},
		{Name: "Synonym", Type: field.TypeString, Size: 300},
		{Name: "por", Type: field.TypeString, Size: 300},
		{Name: "Type", Type: field.TypeString, Size: 300},
		{Name: "width_spisok", Type: field.TypeFloat64},
		{Name: "owner_id", Type: field.TypeString, Nullable: true, Size: 36},
	}
	// MdRekvizitsTable holds the schema information for the "md_rekvizits" table.
	MdRekvizitsTable = &schema.Table{
		Name:       "md_rekvizits",
		Columns:    MdRekvizitsColumns,
		PrimaryKey: []*schema.Column{MdRekvizitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "md_rekvizits_md_tabels_mdrekvizits",
				Columns:    []*schema.Column{MdRekvizitsColumns[6]},
				RefColumns: []*schema.Column{MdTabelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MdSubSystemsColumns holds the columns for the "md_sub_systems" table.
	MdSubSystemsColumns = []*schema.Column{
		{Name: "ID", Type: field.TypeString, Unique: true, Size: 36},
		{Name: "Nameeng", Type: field.TypeString, Size: 300},
		{Name: "Synonym", Type: field.TypeString, Size: 150},
		{Name: "Por", Type: field.TypeString},
		{Name: "Parent", Type: field.TypeString, Nullable: true, Size: 36},
	}
	// MdSubSystemsTable holds the schema information for the "md_sub_systems" table.
	MdSubSystemsTable = &schema.Table{
		Name:       "md_sub_systems",
		Columns:    MdSubSystemsColumns,
		PrimaryKey: []*schema.Column{MdSubSystemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "md_sub_systems_md_sub_systems_child_mdsubsystems",
				Columns:    []*schema.Column{MdSubSystemsColumns[4]},
				RefColumns: []*schema.Column{MdSubSystemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MdTabelsColumns holds the columns for the "md_tabels" table.
	MdTabelsColumns = []*schema.Column{
		{Name: "ID", Type: field.TypeString, Unique: true, Size: 36},
		{Name: "Nameeng", Type: field.TypeString, Size: 300},
		{Name: "Synonym", Type: field.TypeString, Size: 300},
		{Name: "Por", Type: field.TypeString},
		{Name: "File", Type: field.TypeString, Size: 300},
		{Name: "Parent", Type: field.TypeString, Nullable: true, Size: 36},
		{Name: "types_id", Type: field.TypeString, Nullable: true, Size: 36},
	}
	// MdTabelsTable holds the schema information for the "md_tabels" table.
	MdTabelsTable = &schema.Table{
		Name:       "md_tabels",
		Columns:    MdTabelsColumns,
		PrimaryKey: []*schema.Column{MdTabelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "md_tabels_md_tabels_child_mdtabel",
				Columns:    []*schema.Column{MdTabelsColumns[5]},
				RefColumns: []*schema.Column{MdTabelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "md_tabels_md_type_tabels_mdtypetabels",
				Columns:    []*schema.Column{MdTabelsColumns[6]},
				RefColumns: []*schema.Column{MdTypeTabelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MdTypeTabelsColumns holds the columns for the "md_type_tabels" table.
	MdTypeTabelsColumns = []*schema.Column{
		{Name: "ID", Type: field.TypeString, Unique: true, Size: 36},
		{Name: "Nameeng", Type: field.TypeString, Size: 300},
		{Name: "Synonym", Type: field.TypeString, Size: 300},
		{Name: "Por", Type: field.TypeString},
		{Name: "Parent", Type: field.TypeString, Nullable: true, Size: 36},
	}
	// MdTypeTabelsTable holds the schema information for the "md_type_tabels" table.
	MdTypeTabelsTable = &schema.Table{
		Name:       "md_type_tabels",
		Columns:    MdTypeTabelsColumns,
		PrimaryKey: []*schema.Column{MdTypeTabelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "md_type_tabels_md_type_tabels_child_mdtypetabels",
				Columns:    []*schema.Column{MdTypeTabelsColumns[4]},
				RefColumns: []*schema.Column{MdTypeTabelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// MdSubSystemsMdtablesColumns holds the columns for the "md_sub_systems_mdtables" table.
	MdSubSystemsMdtablesColumns = []*schema.Column{
		{Name: "md_sub_systems_id", Type: field.TypeString, Size: 36},
		{Name: "md_tabel_id", Type: field.TypeString, Size: 36},
	}
	// MdSubSystemsMdtablesTable holds the schema information for the "md_sub_systems_mdtables" table.
	MdSubSystemsMdtablesTable = &schema.Table{
		Name:       "md_sub_systems_mdtables",
		Columns:    MdSubSystemsMdtablesColumns,
		PrimaryKey: []*schema.Column{MdSubSystemsMdtablesColumns[0], MdSubSystemsMdtablesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "md_sub_systems_mdtables_md_sub_systems_id",
				Columns:    []*schema.Column{MdSubSystemsMdtablesColumns[0]},
				RefColumns: []*schema.Column{MdSubSystemsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "md_sub_systems_mdtables_md_tabel_id",
				Columns:    []*schema.Column{MdSubSystemsMdtablesColumns[1]},
				RefColumns: []*schema.Column{MdTabelsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MdRekvizitsTable,
		MdSubSystemsTable,
		MdTabelsTable,
		MdTypeTabelsTable,
		MdSubSystemsMdtablesTable,
	}
)

func init() {
	MdRekvizitsTable.ForeignKeys[0].RefTable = MdTabelsTable
	MdSubSystemsTable.ForeignKeys[0].RefTable = MdSubSystemsTable
	MdTabelsTable.ForeignKeys[0].RefTable = MdTabelsTable
	MdTabelsTable.ForeignKeys[1].RefTable = MdTypeTabelsTable
	MdTypeTabelsTable.ForeignKeys[0].RefTable = MdTypeTabelsTable
	MdSubSystemsMdtablesTable.ForeignKeys[0].RefTable = MdSubSystemsTable
	MdSubSystemsMdtablesTable.ForeignKeys[1].RefTable = MdTabelsTable
}
