// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"fynegui/ent/mdforms"
	"fynegui/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MDFormsQuery is the builder for querying MDForms entities.
type MDFormsQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MDForms
	// eager-loading edges.
	withChildMdforms  *MDFormsQuery
	withParentMdforms *MDFormsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MDFormsQuery builder.
func (mfq *MDFormsQuery) Where(ps ...predicate.MDForms) *MDFormsQuery {
	mfq.predicates = append(mfq.predicates, ps...)
	return mfq
}

// Limit adds a limit step to the query.
func (mfq *MDFormsQuery) Limit(limit int) *MDFormsQuery {
	mfq.limit = &limit
	return mfq
}

// Offset adds an offset step to the query.
func (mfq *MDFormsQuery) Offset(offset int) *MDFormsQuery {
	mfq.offset = &offset
	return mfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mfq *MDFormsQuery) Unique(unique bool) *MDFormsQuery {
	mfq.unique = &unique
	return mfq
}

// Order adds an order step to the query.
func (mfq *MDFormsQuery) Order(o ...OrderFunc) *MDFormsQuery {
	mfq.order = append(mfq.order, o...)
	return mfq
}

// QueryChildMdforms chains the current query on the "child_mdforms" edge.
func (mfq *MDFormsQuery) QueryChildMdforms() *MDFormsQuery {
	query := &MDFormsQuery{config: mfq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mfq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mdforms.Table, mdforms.FieldID, selector),
			sqlgraph.To(mdforms.Table, mdforms.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, mdforms.ChildMdformsTable, mdforms.ChildMdformsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mfq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParentMdforms chains the current query on the "parent_mdforms" edge.
func (mfq *MDFormsQuery) QueryParentMdforms() *MDFormsQuery {
	query := &MDFormsQuery{config: mfq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mfq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mdforms.Table, mdforms.FieldID, selector),
			sqlgraph.To(mdforms.Table, mdforms.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mdforms.ParentMdformsTable, mdforms.ParentMdformsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mfq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MDForms entity from the query.
// Returns a *NotFoundError when no MDForms was found.
func (mfq *MDFormsQuery) First(ctx context.Context) (*MDForms, error) {
	nodes, err := mfq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mdforms.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mfq *MDFormsQuery) FirstX(ctx context.Context) *MDForms {
	node, err := mfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MDForms ID from the query.
// Returns a *NotFoundError when no MDForms ID was found.
func (mfq *MDFormsQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = mfq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mdforms.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mfq *MDFormsQuery) FirstIDX(ctx context.Context) string {
	id, err := mfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MDForms entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MDForms entity is found.
// Returns a *NotFoundError when no MDForms entities are found.
func (mfq *MDFormsQuery) Only(ctx context.Context) (*MDForms, error) {
	nodes, err := mfq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mdforms.Label}
	default:
		return nil, &NotSingularError{mdforms.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mfq *MDFormsQuery) OnlyX(ctx context.Context) *MDForms {
	node, err := mfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MDForms ID in the query.
// Returns a *NotSingularError when more than one MDForms ID is found.
// Returns a *NotFoundError when no entities are found.
func (mfq *MDFormsQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = mfq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mdforms.Label}
	default:
		err = &NotSingularError{mdforms.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mfq *MDFormsQuery) OnlyIDX(ctx context.Context) string {
	id, err := mfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MDFormsSlice.
func (mfq *MDFormsQuery) All(ctx context.Context) ([]*MDForms, error) {
	if err := mfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mfq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mfq *MDFormsQuery) AllX(ctx context.Context) []*MDForms {
	nodes, err := mfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MDForms IDs.
func (mfq *MDFormsQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := mfq.Select(mdforms.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mfq *MDFormsQuery) IDsX(ctx context.Context) []string {
	ids, err := mfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mfq *MDFormsQuery) Count(ctx context.Context) (int, error) {
	if err := mfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mfq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mfq *MDFormsQuery) CountX(ctx context.Context) int {
	count, err := mfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mfq *MDFormsQuery) Exist(ctx context.Context) (bool, error) {
	if err := mfq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mfq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mfq *MDFormsQuery) ExistX(ctx context.Context) bool {
	exist, err := mfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MDFormsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mfq *MDFormsQuery) Clone() *MDFormsQuery {
	if mfq == nil {
		return nil
	}
	return &MDFormsQuery{
		config:            mfq.config,
		limit:             mfq.limit,
		offset:            mfq.offset,
		order:             append([]OrderFunc{}, mfq.order...),
		predicates:        append([]predicate.MDForms{}, mfq.predicates...),
		withChildMdforms:  mfq.withChildMdforms.Clone(),
		withParentMdforms: mfq.withParentMdforms.Clone(),
		// clone intermediate query.
		sql:    mfq.sql.Clone(),
		path:   mfq.path,
		unique: mfq.unique,
	}
}

// WithChildMdforms tells the query-builder to eager-load the nodes that are connected to
// the "child_mdforms" edge. The optional arguments are used to configure the query builder of the edge.
func (mfq *MDFormsQuery) WithChildMdforms(opts ...func(*MDFormsQuery)) *MDFormsQuery {
	query := &MDFormsQuery{config: mfq.config}
	for _, opt := range opts {
		opt(query)
	}
	mfq.withChildMdforms = query
	return mfq
}

// WithParentMdforms tells the query-builder to eager-load the nodes that are connected to
// the "parent_mdforms" edge. The optional arguments are used to configure the query builder of the edge.
func (mfq *MDFormsQuery) WithParentMdforms(opts ...func(*MDFormsQuery)) *MDFormsQuery {
	query := &MDFormsQuery{config: mfq.config}
	for _, opt := range opts {
		opt(query)
	}
	mfq.withParentMdforms = query
	return mfq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Idform string `json:"Родитель,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MDForms.Query().
//		GroupBy(mdforms.FieldIdform).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (mfq *MDFormsQuery) GroupBy(field string, fields ...string) *MDFormsGroupBy {
	group := &MDFormsGroupBy{config: mfq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mfq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Idform string `json:"Родитель,omitempty"`
//	}
//
//	client.MDForms.Query().
//		Select(mdforms.FieldIdform).
//		Scan(ctx, &v)
//
func (mfq *MDFormsQuery) Select(fields ...string) *MDFormsSelect {
	mfq.fields = append(mfq.fields, fields...)
	return &MDFormsSelect{MDFormsQuery: mfq}
}

func (mfq *MDFormsQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mfq.fields {
		if !mdforms.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mfq.path != nil {
		prev, err := mfq.path(ctx)
		if err != nil {
			return err
		}
		mfq.sql = prev
	}
	return nil
}

func (mfq *MDFormsQuery) sqlAll(ctx context.Context) ([]*MDForms, error) {
	var (
		nodes       = []*MDForms{}
		_spec       = mfq.querySpec()
		loadedTypes = [2]bool{
			mfq.withChildMdforms != nil,
			mfq.withParentMdforms != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &MDForms{config: mfq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, mfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := mfq.withChildMdforms; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[string]*MDForms)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.ChildMdforms = []*MDForms{}
		}
		query.Where(predicate.MDForms(func(s *sql.Selector) {
			s.Where(sql.InValues(mdforms.ChildMdformsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.Parent
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "parent" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.ChildMdforms = append(node.Edges.ChildMdforms, n)
		}
	}

	if query := mfq.withParentMdforms; query != nil {
		ids := make([]string, 0, len(nodes))
		nodeids := make(map[string][]*MDForms)
		for i := range nodes {
			fk := nodes[i].Parent
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(mdforms.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "parent" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.ParentMdforms = n
			}
		}
	}

	return nodes, nil
}

func (mfq *MDFormsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mfq.querySpec()
	_spec.Node.Columns = mfq.fields
	if len(mfq.fields) > 0 {
		_spec.Unique = mfq.unique != nil && *mfq.unique
	}
	return sqlgraph.CountNodes(ctx, mfq.driver, _spec)
}

func (mfq *MDFormsQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := mfq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (mfq *MDFormsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mdforms.Table,
			Columns: mdforms.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: mdforms.FieldID,
			},
		},
		From:   mfq.sql,
		Unique: true,
	}
	if unique := mfq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mfq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mdforms.FieldID)
		for i := range fields {
			if fields[i] != mdforms.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mfq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mfq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mfq *MDFormsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mfq.driver.Dialect())
	t1 := builder.Table(mdforms.Table)
	columns := mfq.fields
	if len(columns) == 0 {
		columns = mdforms.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mfq.sql != nil {
		selector = mfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mfq.unique != nil && *mfq.unique {
		selector.Distinct()
	}
	for _, p := range mfq.predicates {
		p(selector)
	}
	for _, p := range mfq.order {
		p(selector)
	}
	if offset := mfq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mfq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MDFormsGroupBy is the group-by builder for MDForms entities.
type MDFormsGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mfgb *MDFormsGroupBy) Aggregate(fns ...AggregateFunc) *MDFormsGroupBy {
	mfgb.fns = append(mfgb.fns, fns...)
	return mfgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mfgb *MDFormsGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mfgb.path(ctx)
	if err != nil {
		return err
	}
	mfgb.sql = query
	return mfgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mfgb *MDFormsGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := mfgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (mfgb *MDFormsGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(mfgb.fields) > 1 {
		return nil, errors.New("ent: MDFormsGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := mfgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mfgb *MDFormsGroupBy) StringsX(ctx context.Context) []string {
	v, err := mfgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mfgb *MDFormsGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mfgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdforms.Label}
	default:
		err = fmt.Errorf("ent: MDFormsGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mfgb *MDFormsGroupBy) StringX(ctx context.Context) string {
	v, err := mfgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (mfgb *MDFormsGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(mfgb.fields) > 1 {
		return nil, errors.New("ent: MDFormsGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := mfgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mfgb *MDFormsGroupBy) IntsX(ctx context.Context) []int {
	v, err := mfgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mfgb *MDFormsGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mfgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdforms.Label}
	default:
		err = fmt.Errorf("ent: MDFormsGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mfgb *MDFormsGroupBy) IntX(ctx context.Context) int {
	v, err := mfgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (mfgb *MDFormsGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(mfgb.fields) > 1 {
		return nil, errors.New("ent: MDFormsGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := mfgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mfgb *MDFormsGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := mfgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mfgb *MDFormsGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mfgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdforms.Label}
	default:
		err = fmt.Errorf("ent: MDFormsGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mfgb *MDFormsGroupBy) Float64X(ctx context.Context) float64 {
	v, err := mfgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (mfgb *MDFormsGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(mfgb.fields) > 1 {
		return nil, errors.New("ent: MDFormsGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := mfgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mfgb *MDFormsGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := mfgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mfgb *MDFormsGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mfgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdforms.Label}
	default:
		err = fmt.Errorf("ent: MDFormsGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mfgb *MDFormsGroupBy) BoolX(ctx context.Context) bool {
	v, err := mfgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mfgb *MDFormsGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mfgb.fields {
		if !mdforms.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mfgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mfgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mfgb *MDFormsGroupBy) sqlQuery() *sql.Selector {
	selector := mfgb.sql.Select()
	aggregation := make([]string, 0, len(mfgb.fns))
	for _, fn := range mfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mfgb.fields)+len(mfgb.fns))
		for _, f := range mfgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mfgb.fields...)...)
}

// MDFormsSelect is the builder for selecting fields of MDForms entities.
type MDFormsSelect struct {
	*MDFormsQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mfs *MDFormsSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mfs.prepareQuery(ctx); err != nil {
		return err
	}
	mfs.sql = mfs.MDFormsQuery.sqlQuery(ctx)
	return mfs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mfs *MDFormsSelect) ScanX(ctx context.Context, v interface{}) {
	if err := mfs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (mfs *MDFormsSelect) Strings(ctx context.Context) ([]string, error) {
	if len(mfs.fields) > 1 {
		return nil, errors.New("ent: MDFormsSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := mfs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mfs *MDFormsSelect) StringsX(ctx context.Context) []string {
	v, err := mfs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (mfs *MDFormsSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mfs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdforms.Label}
	default:
		err = fmt.Errorf("ent: MDFormsSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mfs *MDFormsSelect) StringX(ctx context.Context) string {
	v, err := mfs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (mfs *MDFormsSelect) Ints(ctx context.Context) ([]int, error) {
	if len(mfs.fields) > 1 {
		return nil, errors.New("ent: MDFormsSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := mfs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mfs *MDFormsSelect) IntsX(ctx context.Context) []int {
	v, err := mfs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (mfs *MDFormsSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mfs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdforms.Label}
	default:
		err = fmt.Errorf("ent: MDFormsSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mfs *MDFormsSelect) IntX(ctx context.Context) int {
	v, err := mfs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (mfs *MDFormsSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(mfs.fields) > 1 {
		return nil, errors.New("ent: MDFormsSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := mfs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mfs *MDFormsSelect) Float64sX(ctx context.Context) []float64 {
	v, err := mfs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (mfs *MDFormsSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mfs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdforms.Label}
	default:
		err = fmt.Errorf("ent: MDFormsSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mfs *MDFormsSelect) Float64X(ctx context.Context) float64 {
	v, err := mfs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (mfs *MDFormsSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(mfs.fields) > 1 {
		return nil, errors.New("ent: MDFormsSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := mfs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mfs *MDFormsSelect) BoolsX(ctx context.Context) []bool {
	v, err := mfs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (mfs *MDFormsSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mfs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdforms.Label}
	default:
		err = fmt.Errorf("ent: MDFormsSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mfs *MDFormsSelect) BoolX(ctx context.Context) bool {
	v, err := mfs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mfs *MDFormsSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mfs.sql.Query()
	if err := mfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
