// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"fynegui/ent/mdforms"
	"fynegui/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MDFormsDelete is the builder for deleting a MDForms entity.
type MDFormsDelete struct {
	config
	hooks    []Hook
	mutation *MDFormsMutation
}

// Where appends a list predicates to the MDFormsDelete builder.
func (mfd *MDFormsDelete) Where(ps ...predicate.MDForms) *MDFormsDelete {
	mfd.mutation.Where(ps...)
	return mfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mfd *MDFormsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mfd.hooks) == 0 {
		affected, err = mfd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MDFormsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mfd.mutation = mutation
			affected, err = mfd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mfd.hooks) - 1; i >= 0; i-- {
			if mfd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mfd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mfd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mfd *MDFormsDelete) ExecX(ctx context.Context) int {
	n, err := mfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mfd *MDFormsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: mdforms.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: mdforms.FieldID,
			},
		},
	}
	if ps := mfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mfd.driver, _spec)
}

// MDFormsDeleteOne is the builder for deleting a single MDForms entity.
type MDFormsDeleteOne struct {
	mfd *MDFormsDelete
}

// Exec executes the deletion query.
func (mfdo *MDFormsDeleteOne) Exec(ctx context.Context) error {
	n, err := mfdo.mfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mdforms.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mfdo *MDFormsDeleteOne) ExecX(ctx context.Context) {
	mfdo.mfd.ExecX(ctx)
}
