// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"fynegui/ent/mdtypetabel"
	"fynegui/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MDTypeTabelDelete is the builder for deleting a MDTypeTabel entity.
type MDTypeTabelDelete struct {
	config
	hooks    []Hook
	mutation *MDTypeTabelMutation
}

// Where appends a list predicates to the MDTypeTabelDelete builder.
func (mttd *MDTypeTabelDelete) Where(ps ...predicate.MDTypeTabel) *MDTypeTabelDelete {
	mttd.mutation.Where(ps...)
	return mttd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mttd *MDTypeTabelDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mttd.hooks) == 0 {
		affected, err = mttd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MDTypeTabelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mttd.mutation = mutation
			affected, err = mttd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mttd.hooks) - 1; i >= 0; i-- {
			if mttd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mttd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mttd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mttd *MDTypeTabelDelete) ExecX(ctx context.Context) int {
	n, err := mttd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mttd *MDTypeTabelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: mdtypetabel.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: mdtypetabel.FieldID,
			},
		},
	}
	if ps := mttd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mttd.driver, _spec)
}

// MDTypeTabelDeleteOne is the builder for deleting a single MDTypeTabel entity.
type MDTypeTabelDeleteOne struct {
	mttd *MDTypeTabelDelete
}

// Exec executes the deletion query.
func (mttdo *MDTypeTabelDeleteOne) Exec(ctx context.Context) error {
	n, err := mttdo.mttd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mdtypetabel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mttdo *MDTypeTabelDeleteOne) ExecX(ctx context.Context) {
	mttdo.mttd.ExecX(ctx)
}
