// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"fynegui/ent/mdtabel"
	"fynegui/ent/mdtypetabel"
	"fynegui/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MDTypeTabelQuery is the builder for querying MDTypeTabel entities.
type MDTypeTabelQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MDTypeTabel
	// eager-loading edges.
	withChildMdtypetabels  *MDTypeTabelQuery
	withParentMdtypetabels *MDTypeTabelQuery
	withMdtypetabels       *MDTabelQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MDTypeTabelQuery builder.
func (mttq *MDTypeTabelQuery) Where(ps ...predicate.MDTypeTabel) *MDTypeTabelQuery {
	mttq.predicates = append(mttq.predicates, ps...)
	return mttq
}

// Limit adds a limit step to the query.
func (mttq *MDTypeTabelQuery) Limit(limit int) *MDTypeTabelQuery {
	mttq.limit = &limit
	return mttq
}

// Offset adds an offset step to the query.
func (mttq *MDTypeTabelQuery) Offset(offset int) *MDTypeTabelQuery {
	mttq.offset = &offset
	return mttq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mttq *MDTypeTabelQuery) Unique(unique bool) *MDTypeTabelQuery {
	mttq.unique = &unique
	return mttq
}

// Order adds an order step to the query.
func (mttq *MDTypeTabelQuery) Order(o ...OrderFunc) *MDTypeTabelQuery {
	mttq.order = append(mttq.order, o...)
	return mttq
}

// QueryChildMdtypetabels chains the current query on the "child_mdtypetabels" edge.
func (mttq *MDTypeTabelQuery) QueryChildMdtypetabels() *MDTypeTabelQuery {
	query := &MDTypeTabelQuery{config: mttq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mttq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mttq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mdtypetabel.Table, mdtypetabel.FieldID, selector),
			sqlgraph.To(mdtypetabel.Table, mdtypetabel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, mdtypetabel.ChildMdtypetabelsTable, mdtypetabel.ChildMdtypetabelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mttq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParentMdtypetabels chains the current query on the "parent_mdtypetabels" edge.
func (mttq *MDTypeTabelQuery) QueryParentMdtypetabels() *MDTypeTabelQuery {
	query := &MDTypeTabelQuery{config: mttq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mttq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mttq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mdtypetabel.Table, mdtypetabel.FieldID, selector),
			sqlgraph.To(mdtypetabel.Table, mdtypetabel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mdtypetabel.ParentMdtypetabelsTable, mdtypetabel.ParentMdtypetabelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mttq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMdtypetabels chains the current query on the "mdtypetabels" edge.
func (mttq *MDTypeTabelQuery) QueryMdtypetabels() *MDTabelQuery {
	query := &MDTabelQuery{config: mttq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mttq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mttq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mdtypetabel.Table, mdtypetabel.FieldID, selector),
			sqlgraph.To(mdtabel.Table, mdtabel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, mdtypetabel.MdtypetabelsTable, mdtypetabel.MdtypetabelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mttq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MDTypeTabel entity from the query.
// Returns a *NotFoundError when no MDTypeTabel was found.
func (mttq *MDTypeTabelQuery) First(ctx context.Context) (*MDTypeTabel, error) {
	nodes, err := mttq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mdtypetabel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mttq *MDTypeTabelQuery) FirstX(ctx context.Context) *MDTypeTabel {
	node, err := mttq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MDTypeTabel ID from the query.
// Returns a *NotFoundError when no MDTypeTabel ID was found.
func (mttq *MDTypeTabelQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = mttq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mdtypetabel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mttq *MDTypeTabelQuery) FirstIDX(ctx context.Context) string {
	id, err := mttq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MDTypeTabel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MDTypeTabel entity is found.
// Returns a *NotFoundError when no MDTypeTabel entities are found.
func (mttq *MDTypeTabelQuery) Only(ctx context.Context) (*MDTypeTabel, error) {
	nodes, err := mttq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mdtypetabel.Label}
	default:
		return nil, &NotSingularError{mdtypetabel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mttq *MDTypeTabelQuery) OnlyX(ctx context.Context) *MDTypeTabel {
	node, err := mttq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MDTypeTabel ID in the query.
// Returns a *NotSingularError when more than one MDTypeTabel ID is found.
// Returns a *NotFoundError when no entities are found.
func (mttq *MDTypeTabelQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = mttq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mdtypetabel.Label}
	default:
		err = &NotSingularError{mdtypetabel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mttq *MDTypeTabelQuery) OnlyIDX(ctx context.Context) string {
	id, err := mttq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MDTypeTabels.
func (mttq *MDTypeTabelQuery) All(ctx context.Context) ([]*MDTypeTabel, error) {
	if err := mttq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mttq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mttq *MDTypeTabelQuery) AllX(ctx context.Context) []*MDTypeTabel {
	nodes, err := mttq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MDTypeTabel IDs.
func (mttq *MDTypeTabelQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := mttq.Select(mdtypetabel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mttq *MDTypeTabelQuery) IDsX(ctx context.Context) []string {
	ids, err := mttq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mttq *MDTypeTabelQuery) Count(ctx context.Context) (int, error) {
	if err := mttq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mttq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mttq *MDTypeTabelQuery) CountX(ctx context.Context) int {
	count, err := mttq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mttq *MDTypeTabelQuery) Exist(ctx context.Context) (bool, error) {
	if err := mttq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mttq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mttq *MDTypeTabelQuery) ExistX(ctx context.Context) bool {
	exist, err := mttq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MDTypeTabelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mttq *MDTypeTabelQuery) Clone() *MDTypeTabelQuery {
	if mttq == nil {
		return nil
	}
	return &MDTypeTabelQuery{
		config:                 mttq.config,
		limit:                  mttq.limit,
		offset:                 mttq.offset,
		order:                  append([]OrderFunc{}, mttq.order...),
		predicates:             append([]predicate.MDTypeTabel{}, mttq.predicates...),
		withChildMdtypetabels:  mttq.withChildMdtypetabels.Clone(),
		withParentMdtypetabels: mttq.withParentMdtypetabels.Clone(),
		withMdtypetabels:       mttq.withMdtypetabels.Clone(),
		// clone intermediate query.
		sql:    mttq.sql.Clone(),
		path:   mttq.path,
		unique: mttq.unique,
	}
}

// WithChildMdtypetabels tells the query-builder to eager-load the nodes that are connected to
// the "child_mdtypetabels" edge. The optional arguments are used to configure the query builder of the edge.
func (mttq *MDTypeTabelQuery) WithChildMdtypetabels(opts ...func(*MDTypeTabelQuery)) *MDTypeTabelQuery {
	query := &MDTypeTabelQuery{config: mttq.config}
	for _, opt := range opts {
		opt(query)
	}
	mttq.withChildMdtypetabels = query
	return mttq
}

// WithParentMdtypetabels tells the query-builder to eager-load the nodes that are connected to
// the "parent_mdtypetabels" edge. The optional arguments are used to configure the query builder of the edge.
func (mttq *MDTypeTabelQuery) WithParentMdtypetabels(opts ...func(*MDTypeTabelQuery)) *MDTypeTabelQuery {
	query := &MDTypeTabelQuery{config: mttq.config}
	for _, opt := range opts {
		opt(query)
	}
	mttq.withParentMdtypetabels = query
	return mttq
}

// WithMdtypetabels tells the query-builder to eager-load the nodes that are connected to
// the "mdtypetabels" edge. The optional arguments are used to configure the query builder of the edge.
func (mttq *MDTypeTabelQuery) WithMdtypetabels(opts ...func(*MDTabelQuery)) *MDTypeTabelQuery {
	query := &MDTabelQuery{config: mttq.config}
	for _, opt := range opts {
		opt(query)
	}
	mttq.withMdtypetabels = query
	return mttq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Nameeng string `json:"ИмяАнгл,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MDTypeTabel.Query().
//		GroupBy(mdtypetabel.FieldNameeng).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (mttq *MDTypeTabelQuery) GroupBy(field string, fields ...string) *MDTypeTabelGroupBy {
	group := &MDTypeTabelGroupBy{config: mttq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mttq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mttq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Nameeng string `json:"ИмяАнгл,omitempty"`
//	}
//
//	client.MDTypeTabel.Query().
//		Select(mdtypetabel.FieldNameeng).
//		Scan(ctx, &v)
//
func (mttq *MDTypeTabelQuery) Select(fields ...string) *MDTypeTabelSelect {
	mttq.fields = append(mttq.fields, fields...)
	return &MDTypeTabelSelect{MDTypeTabelQuery: mttq}
}

func (mttq *MDTypeTabelQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mttq.fields {
		if !mdtypetabel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mttq.path != nil {
		prev, err := mttq.path(ctx)
		if err != nil {
			return err
		}
		mttq.sql = prev
	}
	return nil
}

func (mttq *MDTypeTabelQuery) sqlAll(ctx context.Context) ([]*MDTypeTabel, error) {
	var (
		nodes       = []*MDTypeTabel{}
		_spec       = mttq.querySpec()
		loadedTypes = [3]bool{
			mttq.withChildMdtypetabels != nil,
			mttq.withParentMdtypetabels != nil,
			mttq.withMdtypetabels != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &MDTypeTabel{config: mttq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, mttq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := mttq.withChildMdtypetabels; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[string]*MDTypeTabel)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.ChildMdtypetabels = []*MDTypeTabel{}
		}
		query.Where(predicate.MDTypeTabel(func(s *sql.Selector) {
			s.Where(sql.InValues(mdtypetabel.ChildMdtypetabelsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.Parent
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "parent" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.ChildMdtypetabels = append(node.Edges.ChildMdtypetabels, n)
		}
	}

	if query := mttq.withParentMdtypetabels; query != nil {
		ids := make([]string, 0, len(nodes))
		nodeids := make(map[string][]*MDTypeTabel)
		for i := range nodes {
			fk := nodes[i].Parent
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(mdtypetabel.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "parent" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.ParentMdtypetabels = n
			}
		}
	}

	if query := mttq.withMdtypetabels; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[string]*MDTypeTabel)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Mdtypetabels = []*MDTabel{}
		}
		query.Where(predicate.MDTabel(func(s *sql.Selector) {
			s.Where(sql.InValues(mdtypetabel.MdtypetabelsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.TypesID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "types_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Mdtypetabels = append(node.Edges.Mdtypetabels, n)
		}
	}

	return nodes, nil
}

func (mttq *MDTypeTabelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mttq.querySpec()
	_spec.Node.Columns = mttq.fields
	if len(mttq.fields) > 0 {
		_spec.Unique = mttq.unique != nil && *mttq.unique
	}
	return sqlgraph.CountNodes(ctx, mttq.driver, _spec)
}

func (mttq *MDTypeTabelQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := mttq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (mttq *MDTypeTabelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mdtypetabel.Table,
			Columns: mdtypetabel.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: mdtypetabel.FieldID,
			},
		},
		From:   mttq.sql,
		Unique: true,
	}
	if unique := mttq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mttq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mdtypetabel.FieldID)
		for i := range fields {
			if fields[i] != mdtypetabel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mttq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mttq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mttq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mttq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mttq *MDTypeTabelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mttq.driver.Dialect())
	t1 := builder.Table(mdtypetabel.Table)
	columns := mttq.fields
	if len(columns) == 0 {
		columns = mdtypetabel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mttq.sql != nil {
		selector = mttq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mttq.unique != nil && *mttq.unique {
		selector.Distinct()
	}
	for _, p := range mttq.predicates {
		p(selector)
	}
	for _, p := range mttq.order {
		p(selector)
	}
	if offset := mttq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mttq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MDTypeTabelGroupBy is the group-by builder for MDTypeTabel entities.
type MDTypeTabelGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mttgb *MDTypeTabelGroupBy) Aggregate(fns ...AggregateFunc) *MDTypeTabelGroupBy {
	mttgb.fns = append(mttgb.fns, fns...)
	return mttgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mttgb *MDTypeTabelGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mttgb.path(ctx)
	if err != nil {
		return err
	}
	mttgb.sql = query
	return mttgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mttgb *MDTypeTabelGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := mttgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (mttgb *MDTypeTabelGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(mttgb.fields) > 1 {
		return nil, errors.New("ent: MDTypeTabelGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := mttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mttgb *MDTypeTabelGroupBy) StringsX(ctx context.Context) []string {
	v, err := mttgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mttgb *MDTypeTabelGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mttgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdtypetabel.Label}
	default:
		err = fmt.Errorf("ent: MDTypeTabelGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mttgb *MDTypeTabelGroupBy) StringX(ctx context.Context) string {
	v, err := mttgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (mttgb *MDTypeTabelGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(mttgb.fields) > 1 {
		return nil, errors.New("ent: MDTypeTabelGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := mttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mttgb *MDTypeTabelGroupBy) IntsX(ctx context.Context) []int {
	v, err := mttgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mttgb *MDTypeTabelGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mttgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdtypetabel.Label}
	default:
		err = fmt.Errorf("ent: MDTypeTabelGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mttgb *MDTypeTabelGroupBy) IntX(ctx context.Context) int {
	v, err := mttgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (mttgb *MDTypeTabelGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(mttgb.fields) > 1 {
		return nil, errors.New("ent: MDTypeTabelGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := mttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mttgb *MDTypeTabelGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := mttgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mttgb *MDTypeTabelGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mttgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdtypetabel.Label}
	default:
		err = fmt.Errorf("ent: MDTypeTabelGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mttgb *MDTypeTabelGroupBy) Float64X(ctx context.Context) float64 {
	v, err := mttgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (mttgb *MDTypeTabelGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(mttgb.fields) > 1 {
		return nil, errors.New("ent: MDTypeTabelGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := mttgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mttgb *MDTypeTabelGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := mttgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mttgb *MDTypeTabelGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mttgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdtypetabel.Label}
	default:
		err = fmt.Errorf("ent: MDTypeTabelGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mttgb *MDTypeTabelGroupBy) BoolX(ctx context.Context) bool {
	v, err := mttgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mttgb *MDTypeTabelGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mttgb.fields {
		if !mdtypetabel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mttgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mttgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mttgb *MDTypeTabelGroupBy) sqlQuery() *sql.Selector {
	selector := mttgb.sql.Select()
	aggregation := make([]string, 0, len(mttgb.fns))
	for _, fn := range mttgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mttgb.fields)+len(mttgb.fns))
		for _, f := range mttgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mttgb.fields...)...)
}

// MDTypeTabelSelect is the builder for selecting fields of MDTypeTabel entities.
type MDTypeTabelSelect struct {
	*MDTypeTabelQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mtts *MDTypeTabelSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mtts.prepareQuery(ctx); err != nil {
		return err
	}
	mtts.sql = mtts.MDTypeTabelQuery.sqlQuery(ctx)
	return mtts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mtts *MDTypeTabelSelect) ScanX(ctx context.Context, v interface{}) {
	if err := mtts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (mtts *MDTypeTabelSelect) Strings(ctx context.Context) ([]string, error) {
	if len(mtts.fields) > 1 {
		return nil, errors.New("ent: MDTypeTabelSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := mtts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mtts *MDTypeTabelSelect) StringsX(ctx context.Context) []string {
	v, err := mtts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (mtts *MDTypeTabelSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mtts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdtypetabel.Label}
	default:
		err = fmt.Errorf("ent: MDTypeTabelSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mtts *MDTypeTabelSelect) StringX(ctx context.Context) string {
	v, err := mtts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (mtts *MDTypeTabelSelect) Ints(ctx context.Context) ([]int, error) {
	if len(mtts.fields) > 1 {
		return nil, errors.New("ent: MDTypeTabelSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := mtts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mtts *MDTypeTabelSelect) IntsX(ctx context.Context) []int {
	v, err := mtts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (mtts *MDTypeTabelSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mtts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdtypetabel.Label}
	default:
		err = fmt.Errorf("ent: MDTypeTabelSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mtts *MDTypeTabelSelect) IntX(ctx context.Context) int {
	v, err := mtts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (mtts *MDTypeTabelSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(mtts.fields) > 1 {
		return nil, errors.New("ent: MDTypeTabelSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := mtts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mtts *MDTypeTabelSelect) Float64sX(ctx context.Context) []float64 {
	v, err := mtts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (mtts *MDTypeTabelSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mtts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdtypetabel.Label}
	default:
		err = fmt.Errorf("ent: MDTypeTabelSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mtts *MDTypeTabelSelect) Float64X(ctx context.Context) float64 {
	v, err := mtts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (mtts *MDTypeTabelSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(mtts.fields) > 1 {
		return nil, errors.New("ent: MDTypeTabelSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := mtts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mtts *MDTypeTabelSelect) BoolsX(ctx context.Context) []bool {
	v, err := mtts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (mtts *MDTypeTabelSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mtts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mdtypetabel.Label}
	default:
		err = fmt.Errorf("ent: MDTypeTabelSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mtts *MDTypeTabelSelect) BoolX(ctx context.Context) bool {
	v, err := mtts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mtts *MDTypeTabelSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mtts.sql.Query()
	if err := mtts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
