// Code generated by entc, DO NOT EDIT.

package mdsubsystems

import (
	"fynegui/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Namerus applies equality check predicate on the "namerus" field. It's identical to NamerusEQ.
func Namerus(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNamerus), v))
	})
}

// Nameeng applies equality check predicate on the "nameeng" field. It's identical to NameengEQ.
func Nameeng(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNameeng), v))
	})
}

// Synonym applies equality check predicate on the "synonym" field. It's identical to SynonymEQ.
func Synonym(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSynonym), v))
	})
}

// Parent applies equality check predicate on the "parent" field. It's identical to ParentEQ.
func Parent(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldParent), v))
	})
}

// NamerusEQ applies the EQ predicate on the "namerus" field.
func NamerusEQ(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNamerus), v))
	})
}

// NamerusNEQ applies the NEQ predicate on the "namerus" field.
func NamerusNEQ(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNamerus), v))
	})
}

// NamerusIn applies the In predicate on the "namerus" field.
func NamerusIn(vs ...string) predicate.MDSubSystems {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDSubSystems(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNamerus), v...))
	})
}

// NamerusNotIn applies the NotIn predicate on the "namerus" field.
func NamerusNotIn(vs ...string) predicate.MDSubSystems {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDSubSystems(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNamerus), v...))
	})
}

// NamerusGT applies the GT predicate on the "namerus" field.
func NamerusGT(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNamerus), v))
	})
}

// NamerusGTE applies the GTE predicate on the "namerus" field.
func NamerusGTE(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNamerus), v))
	})
}

// NamerusLT applies the LT predicate on the "namerus" field.
func NamerusLT(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNamerus), v))
	})
}

// NamerusLTE applies the LTE predicate on the "namerus" field.
func NamerusLTE(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNamerus), v))
	})
}

// NamerusContains applies the Contains predicate on the "namerus" field.
func NamerusContains(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNamerus), v))
	})
}

// NamerusHasPrefix applies the HasPrefix predicate on the "namerus" field.
func NamerusHasPrefix(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNamerus), v))
	})
}

// NamerusHasSuffix applies the HasSuffix predicate on the "namerus" field.
func NamerusHasSuffix(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNamerus), v))
	})
}

// NamerusEqualFold applies the EqualFold predicate on the "namerus" field.
func NamerusEqualFold(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNamerus), v))
	})
}

// NamerusContainsFold applies the ContainsFold predicate on the "namerus" field.
func NamerusContainsFold(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNamerus), v))
	})
}

// NameengEQ applies the EQ predicate on the "nameeng" field.
func NameengEQ(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNameeng), v))
	})
}

// NameengNEQ applies the NEQ predicate on the "nameeng" field.
func NameengNEQ(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNameeng), v))
	})
}

// NameengIn applies the In predicate on the "nameeng" field.
func NameengIn(vs ...string) predicate.MDSubSystems {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDSubSystems(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNameeng), v...))
	})
}

// NameengNotIn applies the NotIn predicate on the "nameeng" field.
func NameengNotIn(vs ...string) predicate.MDSubSystems {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDSubSystems(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNameeng), v...))
	})
}

// NameengGT applies the GT predicate on the "nameeng" field.
func NameengGT(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNameeng), v))
	})
}

// NameengGTE applies the GTE predicate on the "nameeng" field.
func NameengGTE(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNameeng), v))
	})
}

// NameengLT applies the LT predicate on the "nameeng" field.
func NameengLT(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNameeng), v))
	})
}

// NameengLTE applies the LTE predicate on the "nameeng" field.
func NameengLTE(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNameeng), v))
	})
}

// NameengContains applies the Contains predicate on the "nameeng" field.
func NameengContains(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNameeng), v))
	})
}

// NameengHasPrefix applies the HasPrefix predicate on the "nameeng" field.
func NameengHasPrefix(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNameeng), v))
	})
}

// NameengHasSuffix applies the HasSuffix predicate on the "nameeng" field.
func NameengHasSuffix(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNameeng), v))
	})
}

// NameengEqualFold applies the EqualFold predicate on the "nameeng" field.
func NameengEqualFold(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNameeng), v))
	})
}

// NameengContainsFold applies the ContainsFold predicate on the "nameeng" field.
func NameengContainsFold(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNameeng), v))
	})
}

// SynonymEQ applies the EQ predicate on the "synonym" field.
func SynonymEQ(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSynonym), v))
	})
}

// SynonymNEQ applies the NEQ predicate on the "synonym" field.
func SynonymNEQ(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSynonym), v))
	})
}

// SynonymIn applies the In predicate on the "synonym" field.
func SynonymIn(vs ...string) predicate.MDSubSystems {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDSubSystems(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSynonym), v...))
	})
}

// SynonymNotIn applies the NotIn predicate on the "synonym" field.
func SynonymNotIn(vs ...string) predicate.MDSubSystems {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDSubSystems(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSynonym), v...))
	})
}

// SynonymGT applies the GT predicate on the "synonym" field.
func SynonymGT(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSynonym), v))
	})
}

// SynonymGTE applies the GTE predicate on the "synonym" field.
func SynonymGTE(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSynonym), v))
	})
}

// SynonymLT applies the LT predicate on the "synonym" field.
func SynonymLT(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSynonym), v))
	})
}

// SynonymLTE applies the LTE predicate on the "synonym" field.
func SynonymLTE(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSynonym), v))
	})
}

// SynonymContains applies the Contains predicate on the "synonym" field.
func SynonymContains(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSynonym), v))
	})
}

// SynonymHasPrefix applies the HasPrefix predicate on the "synonym" field.
func SynonymHasPrefix(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSynonym), v))
	})
}

// SynonymHasSuffix applies the HasSuffix predicate on the "synonym" field.
func SynonymHasSuffix(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSynonym), v))
	})
}

// SynonymEqualFold applies the EqualFold predicate on the "synonym" field.
func SynonymEqualFold(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSynonym), v))
	})
}

// SynonymContainsFold applies the ContainsFold predicate on the "synonym" field.
func SynonymContainsFold(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSynonym), v))
	})
}

// ParentEQ applies the EQ predicate on the "parent" field.
func ParentEQ(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldParent), v))
	})
}

// ParentNEQ applies the NEQ predicate on the "parent" field.
func ParentNEQ(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldParent), v))
	})
}

// ParentIn applies the In predicate on the "parent" field.
func ParentIn(vs ...string) predicate.MDSubSystems {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDSubSystems(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldParent), v...))
	})
}

// ParentNotIn applies the NotIn predicate on the "parent" field.
func ParentNotIn(vs ...string) predicate.MDSubSystems {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.MDSubSystems(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldParent), v...))
	})
}

// ParentGT applies the GT predicate on the "parent" field.
func ParentGT(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldParent), v))
	})
}

// ParentGTE applies the GTE predicate on the "parent" field.
func ParentGTE(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldParent), v))
	})
}

// ParentLT applies the LT predicate on the "parent" field.
func ParentLT(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldParent), v))
	})
}

// ParentLTE applies the LTE predicate on the "parent" field.
func ParentLTE(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldParent), v))
	})
}

// ParentContains applies the Contains predicate on the "parent" field.
func ParentContains(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldParent), v))
	})
}

// ParentHasPrefix applies the HasPrefix predicate on the "parent" field.
func ParentHasPrefix(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldParent), v))
	})
}

// ParentHasSuffix applies the HasSuffix predicate on the "parent" field.
func ParentHasSuffix(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldParent), v))
	})
}

// ParentIsNil applies the IsNil predicate on the "parent" field.
func ParentIsNil() predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldParent)))
	})
}

// ParentNotNil applies the NotNil predicate on the "parent" field.
func ParentNotNil() predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldParent)))
	})
}

// ParentEqualFold applies the EqualFold predicate on the "parent" field.
func ParentEqualFold(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldParent), v))
	})
}

// ParentContainsFold applies the ContainsFold predicate on the "parent" field.
func ParentContainsFold(v string) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldParent), v))
	})
}

// HasChildMdsubsystems applies the HasEdge predicate on the "child_mdsubsystems" edge.
func HasChildMdsubsystems() predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ChildMdsubsystemsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildMdsubsystemsTable, ChildMdsubsystemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildMdsubsystemsWith applies the HasEdge predicate on the "child_mdsubsystems" edge with a given conditions (other predicates).
func HasChildMdsubsystemsWith(preds ...predicate.MDSubSystems) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildMdsubsystemsTable, ChildMdsubsystemsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasParentMdsubsystems applies the HasEdge predicate on the "parent_mdsubsystems" edge.
func HasParentMdsubsystems() predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ParentMdsubsystemsTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentMdsubsystemsTable, ParentMdsubsystemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentMdsubsystemsWith applies the HasEdge predicate on the "parent_mdsubsystems" edge with a given conditions (other predicates).
func HasParentMdsubsystemsWith(preds ...predicate.MDSubSystems) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentMdsubsystemsTable, ParentMdsubsystemsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMdtables applies the HasEdge predicate on the "mdtables" edge.
func HasMdtables() predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MdtablesTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, MdtablesTable, MdtablesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMdtablesWith applies the HasEdge predicate on the "mdtables" edge with a given conditions (other predicates).
func HasMdtablesWith(preds ...predicate.MDTabel) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MdtablesInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, MdtablesTable, MdtablesPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MDSubSystems) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MDSubSystems) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MDSubSystems) predicate.MDSubSystems {
	return predicate.MDSubSystems(func(s *sql.Selector) {
		p(s.Not())
	})
}
